spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  
  jpa:
    properties:
      driver-class-name: org.postgresql.Driver
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

jwt:
  secret: mysecretkey
  expiration: 3600000

sonarcude: sqp_b7961e01aeffd425ca41b5ef4abcec956fb5694d

management:
  endpoints:
    access:
      default: read-only
    web:
      exposure:
        include:
        - health
        - metrics
        - prometheus  
  endpoint:
    health:
      show-details: always    
      show-components: always  
    metrics:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true
    